### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/chemcalculatorrr#10]
- [x] after all functions and test are completed, run `devtools::test()`
- [x] add covr package as suggested dependency
- [x] add other packages used eg stringr (`use_package("stringr")`
- [x] check the R package building guide if anything is missing
