### ISSUE TITLE
Milestone 2 Project structure and contribution/readme

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/chemcalculatorrr#3]
- [x]  MIT license

- [x] Use usethis::use_code_of_conduct to add a code of conduct. You may want to customize it further to suit your group.

- [x] Add the team members as authors to the DESCRIPTION file.

- [x] Use usethis::use_tidy_contributing() to add a CONTRIBUTING.md file to your package.

README: 
- [x] a summary paragraph that describes the project at a high level

- [x] a bulleted list of the functions (and datasets if applicable) that will be included in the package (this should be a 1-2 sentence description for each function/dataset)

- [x]  a paragraph describing where your packages fit into the R ecosystem (are there any other R packages that have the same/similar functionality? Provide links to any that do. If none exist, then clearly state this as well).
