### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by jo4356** [UBC-MDS/chemcalculatorrr#33]
Continuous integration:
- [x] #35
- [x] #36
https://github.com/r-lib/actions/blob/master/.github/workflows/check-standard.yaml
https://github.com/r-lib/actions/blob/master/.github/workflows/test-coverage.yaml

Documentation:
- [x] use vignette package-wide documentation in R, 
- [x] pkgdown R package to set up a website for your package
- [x] include a full usage demonstration of all your package functions (this means a runnable example - give them data!) in your vignette
- [x] include installation instructions in the README.Rmd file
- [x] examine Roxygen2 documentation of your functions to make sure it is clear
